# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-6.0479e+23,  1.1757e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix

In [164]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3375, 0.5623, 0.9471],
        [0.0579, 0.4072, 0.2635],
        [0.3897, 0.8324, 0.4098],
        [0.7428, 0.7461, 0.5091],
        [0.2151, 0.5171, 0.8642]])


Get its size

In [165]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [166]:
x[1:3] = 2
print(x)

tensor([[0.3375, 0.5623, 0.9471],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.7428, 0.7461, 0.5091],
        [0.2151, 0.5171, 0.8642]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [167]:
# 1. Make a tensor of size (2, 17)
ans1 = torch.Tensor(2,17)
# 2. Make a torch.FloatTensor of size (3, 1)
ans2 = torch.FloatTensor(3,1)
# 3. Make a torch.LongTensor of size (5, 2, 1)
ans3 = torch.LongTensor(5,2,1)
#   - fill the entire tensor with 7s
ans4 = torch.fill(ans3, 7)
# 4. Make a torch.ByteTensor of size (5,)
ans5 = torch.ByteTensor(5,1)
#   - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
ans5[1:4] = 1
print(ans5)

tensor([[1],
        [1],
        [1],
        [1],
        [1]], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [168]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2404, 1.3798, 1.7258],
        [2.2791, 2.0257, 2.8474],
        [2.7345, 2.6626, 2.8957],
        [1.3171, 1.1106, 0.9579],
        [1.1107, 1.2377, 0.8652]])


### 2.2 Addition: syntax 2

In [169]:
print(torch.add(x, y))

tensor([[1.2404, 1.3798, 1.7258],
        [2.2791, 2.0257, 2.8474],
        [2.7345, 2.6626, 2.8957],
        [1.3171, 1.1106, 0.9579],
        [1.1107, 1.2377, 0.8652]])


### 2.3 Addition: giving an output tensor

In [170]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2404, 1.3798, 1.7258],
        [2.2791, 2.0257, 2.8474],
        [2.7345, 2.6626, 2.8957],
        [1.3171, 1.1106, 0.9579],
        [1.1107, 1.2377, 0.8652]])


### 2.4 Addition: in-place

adds `x` to `y`

In [171]:
y.add_(x)
print(y)

tensor([[1.2404, 1.3798, 1.7258],
        [2.2791, 2.0257, 2.8474],
        [2.7345, 2.6626, 2.8957],
        [1.3171, 1.1106, 0.9579],
        [1.1107, 1.2377, 0.8652]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [172]:
print(x[:, 1])

tensor([0.5623, 2.0000, 2.0000, 0.7461, 0.5171])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [ ]:
# 1) elementwise multiply (out-of-place)
x = torch.rand(3, 3)
y = torch.rand(3, 3)
res = torch.mul(x, y)          # or: x * y

# 2) same, but truly in-place
x2 = x.clone()
res2 = x2.mul_(y)              # modifies x2; x remains unchanged

# 3) elementwise division
q1 = torch.div(x, y)           # or: x / y
# floor division example:
q_floor = torch.div(x, y, rounding_mode="floor")
 
# 4) matrix multiplication (2x4) @ (4x2) -> (2x2)
A = torch.randn(2, 4)
B = torch.randn(4, 2)
M = torch.matmul(A, B)         # or: A @ B


True


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [174]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [175]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [176]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [177]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [187]:
# # Assignment

# 1. create a tensor of size (5, 2) containing ones
tens = torch.Tensor(5,2)
tens.fill_(1)
# 2. now convert it to a NumPy array
tens_num = tens.numpy()
# 3. now convert it back to a torch tensor
tens_num_tens = torch.from_numpy(tens_num)


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [188]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
